// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: books.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const findAllBooks = `-- name: FindAllBooks :many
SELECT id, name, author, price, created_at, likes FROM books ORDER BY created_at DESC
`

func (q *Queries) FindAllBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, findAllBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Author,
			&i.Price,
			&i.CreatedAt,
			&i.Likes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBook = `-- name: InsertBook :one
INSERT INTO books (
  name,
  author,
  price
)
VALUES (
  $1,
  $2,
  $3
)
RETURNING id, name, author, price, created_at, likes
`

type InsertBookParams struct {
	Name   string         `json:"name"`
	Author string         `json:"author"`
	Price  pgtype.Numeric `json:"price"`
}

func (q *Queries) InsertBook(ctx context.Context, arg InsertBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, insertBook, arg.Name, arg.Author, arg.Price)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Price,
		&i.CreatedAt,
		&i.Likes,
	)
	return i, err
}

const like = `-- name: Like :one
UPDATE books
SET
  likes = likes + 1
WHERE id = $1
    AND ($2::boolean IS NULL OR true)
RETURNING likes, 1 as _dummy
`

type LikeParams struct {
	ID    uuid.UUID `json:"id"`
	Dummy bool      `json:"dummy"`
}

type LikeRow struct {
	Likes int64 `json:"likes"`
	Dummy int32 `json:"_dummy"`
}

func (q *Queries) Like(ctx context.Context, arg LikeParams) (LikeRow, error) {
	row := q.db.QueryRow(ctx, like, arg.ID, arg.Dummy)
	var i LikeRow
	err := row.Scan(&i.Likes, &i.Dummy)
	return i, err
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET
  name = COALESCE($1, name),
  author = COALESCE($2, author),
  price = COALESCE($3, price)
WHERE id = $4
RETURNING id, name, author, price, created_at, likes
`

type UpdateBookParams struct {
	Name   *string        `json:"name"`
	Author *string        `json:"author"`
	Price  pgtype.Numeric `json:"price"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.Name,
		arg.Author,
		arg.Price,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Price,
		&i.CreatedAt,
		&i.Likes,
	)
	return i, err
}
