// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package repository

import (
	"context"
)

const insertItem = `-- name: InsertItem :one
INSERT INTO items (id, name, value)
VALUES (uuid_generate_v4(), $1, $2)
RETURNING id, name, value
`

type InsertItemParams struct {
	Name  string `json:"name"`
	Value int32  `json:"value"`
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem, arg.Name, arg.Value)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Value)
	return i, err
}
