// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID     uuid.UUID      `json:"id"`
	Name   string         `json:"name"`
	Author string         `json:"author"`
	Price  pgtype.Numeric `json:"price"`
}
