// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repository

import (
	"context"
)

const findAllPlayers = `-- name: FindAllPlayers :many
SELECT id, username, email, created_at, score FROM players
`

func (q *Queries) FindAllPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, findAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.CreatedAt,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertItem = `-- name: InsertItem :one
INSERT INTO items (id, name, value)
VALUES (uuid_generate_v4(), $1, $2)
RETURNING id, name, value
`

type InsertItemParams struct {
	Name  string `json:"name"`
	Value int32  `json:"value"`
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, insertItem, arg.Name, arg.Value)
	var i Item
	err := row.Scan(&i.ID, &i.Name, &i.Value)
	return i, err
}
