// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertUser = `-- name: InsertUser :one
INSERT INTO users (
  name,
  email,
  password
) VALUES (
  $1,
  $2,
  crypt($3, gen_salt('bf'))
) RETURNING 
  id,
  name,
  email,
  created_at
`

type InsertUserParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Crypt string `json:"crypt"`
}

type InsertUserRow struct {
	ID        uuid.UUID        `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (InsertUserRow, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Name, arg.Email, arg.Crypt)
	var i InsertUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
